version: '2.2'
services:
  lighttpd-server:
    build:
      context: ./lighttpd/
    ports:
      - "80:80"
    networks:
      - db-network

  postgresql-server:
    build:
      context: ./postgresql/
    ports:
      - "5432:5432"
    networks:
      - db-network

  wildfly-server:
    build:
      context: ./wildfly/
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - db-network
    volumes:
      - ./wildfly/volumes/wildfy-deployments:/opt/jboss/wildfly/standalone/deployments
      - ./wildfly/volumes/wildfy-configuration:/opt/jboss/wildfly/standalone/configuration
      - ./wildfly/volumes/grails-configuration:/opt/jboss/.grails

  keycloak:
    image: jboss/keycloak:3.4.3.Final
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - POSTGRES_ADDR=postgresql-server
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_PORT_5432_TCP_ADDR=postgresql-server
    ports:
      - "8081:8080"
    depends_on:
      - postgresql-server
    networks:
      - db-network

  irct:
    build:
      context: ./irct/
    ports:
      - "8082:8080"
      - "9992:9990"
    networks:
      - db-network
    environment:
      - IRCT_SRC_DIR=/irct-src
      - IRCT_DB_URL=jdbc:postgresql://postgresql-server:5432/irct
      - IRCT_DB_USER=irct
      - IRCT_DB_PW=pFjy3EjDVwLfT2rB9xkK
      - IRCT_OIDC_ADDR=keycloak
      - IRCT_OIDC_REDIRECT=/IRCT-UI/token.html
      - IRCT_OIDC_CLIENT_ID=irct
      - IRCT_OIDC_CLIENT_SECRET=rCwDRtQM510Du5bYGCHfLClM8XMph95aJwNsCr6MAucIiSxGeN5pcni3QRJqlYcc
      - IRCT_OIDC_USER_FIELD=email
      - IRCT_KEY_TIMEOUT=720
      - IRCT_WHITELIST_FILE=false
      - IRCT_RESULT_DATA_FOLDER=scratch/irct
      - IRCT_OIDC_JWKS_ADDR=http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs
    volumes:
      - ../:/irct-src
      - mvn-repo:/opt/jboss/.m2/repository
      - ./irct/volumes/wildfly-configuration:/opt/jboss/wildfly/standalone/configuration
      - ./irct/volumes/wildfly-deployments:/opt/jboss/wildfly/standalone/deployments

volumes:
  mvn-repo:

networks:
  db-network:
    driver: bridge
